name: Validate and Test File Manager Script

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    name: Validate and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Make the Script Executable
        run: chmod +x ./File_Manager_Script.sh

      - name: Simulate User Input
        run: |
          ./File_Manager_Script.sh <<EOF
          1
          testfile.txt
          3
          6
          EOF
