name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install ShellCheck
      run: sudo apt-get install -y shellcheck

    - name: List Files
      run: ls -R

    - name: Validate Bash Script with ShellCheck
      run: shellcheck ./File_Manager_Script.sh # Ensure this path matches the actual file location

    - name: Run Script Tests
      run: |
        chmod +x ./File_Manager_Script.sh
        ./File_Manager_Script.sh
